# Generated by Django 3.2.25 on 2025-11-15 03:40

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20251113_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='skill_categories',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=djongo.models.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill_categories',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
